sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t philipladendorf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true philipladendorf/react-test npm test -- --coverage

after_success:
  - docker build -t philipladendorf/multi-client ./client
  - docker build -t philipladendorf/multi-nginx ./nginx
  - docker build -t philipladendorf/multi-api ./api
  - docker build -t philipladendorf/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push philipladendorf/multi-client
  - docker push philipladendorf/multi-nginx
  - docker push philipladendorf/multi-api
  - docker push philipladendorf/multi-worker
# Tell Elastic Beanstalk to update the application with the new images
deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'Multi-Docker-Env'
  env: 'Multi-Docker-Env-2'
  bucket_name: 'elasticbeanstalk-eu-central-1-408165109665'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
